pirogramming/Healthtant

- config/settings.py
- templates/account/login.html
login.html 초안 작성 및 account 폴더 구조 개선
- login.html 초안 작성
- account 폴더 구조 개선
- setting 파일 수정
> [Feat] login.html 초안 작성 및 account 폴더 구조 개선

- .github/workflows/main.yml
GitHub Actions를 활용한 CI/CD 구축을 위한 main.yml 파일 생성
- main 브랜치 푸시 시 자동으로 서버에 배포되도록 GitHub Actions 워크플로우 추가
- SSH를 통해 서버 접속 후 docker-compose 기반으로 서비스 재배포
- 마이그레이션 자동 실행
> [CI] cicd 구축을 위한 main.yml 파일 생성

- diets/views.py
내 식사 수정 및 삭제 api 구현
- diet_update 뷰에 PATCH, DELETE 메소드 분기 처리하여 구현
- 앞서 모든 뷰가 render, redirect 를 반환하도록 구현했기 때문에 해당 뷰도 redirect 하도록 구현했습니다.
- 추후 JsonResponse 말고 바닐라 파이썬 방식으로 프론트에서 받아야 할 경우 수정해야 할 가능성 있습니다.
> [Feat] 식사 수정 및 삭제 뷰 구현 완료

- config/settings.py
- config/urls.py
- main/admin.py
- main/apps.py
- main/models.py
- main/tests.py
- main/urls.py
- main/views.py
- templates/main/main_mainpage.html
main 앱 생성, main.html 연결
- 메인페이지를 보고싶은 마음에 앱 생성
- models.py, view.py 정도만 설정했어요
> 메인이 잘 만들어졌는지 너무 궁금한 나머지 프론트가 이정도만 작업했습니다..
> [feat] main 앱 생성, main.html 연결

- accounts/views.py
import 추가
- views.py 함수에 import 값 추가
> [Fix] import 추가

- templates/main/main_base.html
- base.html의 nav바에 있는 식단관리, 분석하기 url을 연결했습니다
- 식단관리, 분석하기 a 태그 내에 href에 url 추가
- 추후 검색 기능과 마이페이지 구현되면 연결 추가 필요합니다
> [Feat] 메인 nav바 식단관리, 분석하기 url 연결

- analysis/views.py
- static/analysis/analysis.css
- templates/analysis/analysis_main.html
fix : 2020 영양소 섭취 평가 차트 수정(js, html부분), style : analysis.css 수정
- analysis 의 view.py에서 색상 변경, 주석 변경
- analysis.css 섹션 1, 2, 3 모두 변경
- 일반분석페이지(analysis_main.html) 약 90% 완성
- (미완성) 2020 영양소 섭취 평가 차트 구분선(가로선) 구현 못함
- 2020 영양소 섭취 평가 차트 구분선(가로선) 없어도 괜찮은 것 같은데 어떻게 생각하시나용??
-있는 부분(아직 수정못한 부분)도  보여드릴게요
> [Fix] 2020 영양소 섭취 평가 차트 수정(js, html부분), [Style] analysis.css 수정

- static/diets/diets_main.css
- static/diets/diets_register.css
- static/diets/diets_search.css
- static/products/product_detail.css
- templates/diets/diets_main.html
- templates/diets/diets_register.html
- templates/diets/diets_search.html
- templates/products/products_detail.html
- 간단한 diets nav바 sticky설정
- 제품상세페이지 css및 디자인을 위한 html 수정
- Summary랑 동일합니다
> [Style] diets nav바 sticky설정, 제품상세페이지 css및 디자인을 위한 html 수정

- static/analysis/analysis.css
- templates/analysis/analysis_main.html
분석main 중 차트 라벨 추가
- 마우스를 올리면 보이게 제작
> [Feat] 분석main 중 차트 라벨 추가

- static/analysis/analysis.css
- static/diets/diets_register.css
- templates/analysis/analysis_main.html
- templates/diets/diets_register.html
- diets 목데이터 제거, WHO 기준 삭제
- diets 목데이터 제거하고 빈 부분 스타일 제작
- WHO 구현 안한다고 해서 버튼 삭제
- 짜잘짜잘한 작업이라 브랜치 안옮기고 기존에 작업하던 곳에 해버렸어요...
> [Refactor] diets 목데이터 제거, WHO 기준 삭제

- static/diets/diets_main.css
- static/diets/diets_search.css
- templates/diets/diets_main.html
- templates/diets/diets_search.html
식단기록페이지 뒤로가기 버튼, 날짜 이동, search input 수정완료
- 
-
> [Style] 식단기록페이지 수정완료

- templates/main/main_base.html
- 하단 nav바의 '내 페이지'와 mypage_profile.html 렌더링 뷰를 연결했습니다.
- Summary와 동일
> [Feat] 하단 nav와 마이페이지 url 연결

- static/analysis/analysis.css
- static/diets/diets_main.css
- templates/diets/diets_form.html
- templates/diets/diets_main.html
> [Style] 식단 기록페이지 정렬조정

- analysis/views.py
- diets/views.py
- mypage/views.py
- static/accounts/login.css
- static/base/login_modal.css
- templates/account/login.html
- templates/analysis/analysis_date.html
- templates/base/base.html
- templates/diets/diets_main.html
- templates/mypage/mypage_profile.html
- templates/products/products_detail.html
base.html 모달창 추가함
- 
- 
Closes
> [Feat] 로그인 유도 모달 구현 완료

- config/settings/base.py
- config/settings/local.py
- static/main/js/main.js
- static/search/css/normal_search.css
- static/search/js/normal_search.js
- templates/main/main_mainpage.html
- templates/search/search_page.html
- 메인페이지 , 일반 검색 페이지 js를 이것저것 건드렸습니다.
- 메인페이지 입력창을 클릭하면 일반 검색 페이지로 이동되도록 이벤트리스너를 추가했습니다.
- 일반 검색 페이지에서 검색을 통해 Ajax로 제품이 출력되도록 구현했습니다. (영양 점수 높은 순서)
- 프론트 파이팅
- 수정할게 조금 있을겁니다...!! 최대한 할 수 있는 만큼은 해뒀어요!! 저는 이제 고급 검색 구현하러 갑니다...
> [Feat] 메인페이지, 일반 검색 페이지 js 추가

- search/urls.py
- search/views.py
- static/diets/diets_main.css
- static/diets/diets_register.css
- static/diets/js/diets_main.js
- static/search/css/search_before.css
- static/search/js/normal_search.js
- static/search/js/search_before.js
- templates/diets/diets_register.html
- templates/search/search_before.html
일반검색페이지 구현 완료입니다!!
마지막까지 우리팀 모두 화이팅 합시다!!
다들 고생이 많아유ㅠㅠ
- 
- 
Closes
> [Feat] 일반 검색 페이지 구현 완료

- analysis/views.py
- search/views.py
- advanced_search_page 뷰 쿼리를 최적화하였습니다. (쿼리문으로 한번에 ORDER_BY 주도록 구현)
- 요약과 동일합니다.
> [Refact] 상세 검색 정렬 기능 최적화

- diets/models.py
- main/views.py
- search/views.py
- 메인 페이지에 출력되는 식품에 랜덤성을 추가했습니다
- 영양점수가 높은 식품이 출력되도록 구현했습니다
- Diet 모델 meal 필드의 length를 10으로 넉넉하게 주기로 했습니다
- 요약과 동일
- 프론트 파이팅
> [Feat] 메인 페이지에 출력되는 식품에 랜덤성 추가 & [Fix] Diet 모델 meal 필드 length 10으로 넉넉하게 늘림

- static/diets/js/diets_main.js
- templates/diets/diets_main.html
> [Fix] 빈 카드 날짜현상 해결

- search/views.py
- static/mypage/mypage_favorite_foods.css
- 백엔드에서 is_favorite 속성을 넘겨주게 구현하여 기존 즐겨찾기 버튼이 가지던 문제를 해결했습니다
- Summary와 동일
- 일반 검색 페이지도 영향이 갈 수 있으니 면밀히 확인해주세요!!
- 미처 확인 못한 오류가 있을 수 있으니 상세 검색 페이지도 면밀히 확인해주세요!!
> [Feat] 상세 검색 페이지 즐겨찾기 오류 해결

- search/views.py
- static/search/js/advanced_search_page.js
- templates/search/advanced_result.html
> [fix] result page header 고침

- templates/diets/diets_upload.html
튜브낀 튜브님이 제보하신 페이네이션 삐리리 해결했습니다
- 
- 
Closes
> [Feat] 식사 등록 페이지 이미지 안 뜸 해결
